apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: myapp
    newName: ghcr.io/rhasanov11/go-hello-world
    newTag: latest
    
replicas:
  - name: my-go-app-deployment  # 🎯 Vacib: Bu ad base qovluğundakı deployment.yaml-da yazılan "name" ilə tam eyni olmalıdır!
    count: 3
