apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1      # Yenilənmə zamanı istənilən saydan (replicas) maksimum neçə ədəd artıq pod yaradıla bilər
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
        - name: go-container
          image: myapp
          ports:
            - containerPort: 8080
