apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

# 🎯 DÜZƏLİŞ: commonLabels əvəzinə yeni standart olan 'labels' istifadə edirik
labels:
  - includeSelectors: true
    pairs:
      app: go-app
