apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 🎯 DÜZƏLİŞ: İmajın adını və teqini mühit qovluğuna köçürdük
images:
  - name: myapp                    # deployment.yaml-dakı orijinal image adı
    newName: ghcr.io/rhasanov11/go-hello-world
    newTag: latest                 # GitHub Actions buranı unikal tag ilə əvəzləyəcək
