name: CD - Production Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'apps/go-app/**'

jobs:
  deploy-to-prod:
    uses: ./github/workflows/reusable-pipeline.yml
    with:
      is_cd: true