name: CI - PR Validation & Scan

on:
  pull_request:
    branches: [ main ]
    paths: [ 'apps/go-app/**' ]

jobs:
  validate:
    uses: ./.github/workflows/reusable-app.yml
    with:
      is_cd: false