name: CI - PR Validation & Scan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/go-app/**'

jobs:
  validate-and-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config: ./apps/go-app/buildkitd.toml

      - name: Test Build Docker Image (No Push)
        uses: docker/build-push-action@v5
        with:
          context: ./apps/go-app
          file: ./apps/go-app/Dockerfile
          push: false
          tags: 172.17.0.1:5000/my-app:pr-test

      - name: Run Trivy Security Scan
        run: |
          docker run --rm aquasec/trivy image --insecure --exit-code 1 --severity CRITICAL,HIGH 172.17.0.1:5000/my-app:pr-test