name: CI - PR Validation & Scan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/go-app/**'

jobs:
  validate-and-scan:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      is_cd: false