name: Local CI/CD Docker Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: github-runner-Y298GQ3YSUqbO

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 172.17.0.1:5000/my-app # Lokal registry ünvanınız və layihə adı
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image to Local Registry
        uses: docker/build-push-action@v5
        with:
          context: ./apps/go-app
          file: ./apps/go-app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max