name: Kontekst Testi

on:
  push:
    branches: [ "main" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sistem melumatlarini oxu
        run: |
          echo "Repozitoriya adi: ${{ github.repository }}"
          echo "Push edən istifadəçi1: ${{ github.actor }}"
          echo "Commit SHA kodu: ${{ github.sha }}"
          echo "İcra olunan Əməliyyat Sistemi: ${{ runner.os }}"